### ISSUE TITLE
App crash after changing GPS type

### ISSUE THREAD

**Issue by keerah** [EarToEarOak/RTLSDR-Scanner#12]
Each time I change GPS type to any other than default the application crashes immediately or after applying changes. Running as admin doesn't help. I am on Windows 10

**Comment by EarToEarOak** [comment]
Thanks
Could you post the error message, I've been unable to replicate the problem?

**Comment by keerah** [comment]
I only have a message that Python's been stopped, then the program exits
![2015-08-27 20-29-09](https://cloud.githubusercontent.com/assets/9025818/9527990/04561458-4cfb-11e5-9599-10745b48bbc2.png)
Sorry it's russian localization, it says python.exe has been stopped, gathering additional info

**Comment by EarToEarOak** [comment]
Thanks, could you try one of the [stand-alone](https://github.com/EarToEarOak/RTLSDR-Scanner/releases/latest) executables and see if you get the same error?

**Comment by keerah** [comment]
Sorry, mates, I couldn't even run it. At first it asked for librtlsdr to be added to PATH. Once I've done it, it asked for the same. Then I've moved the executable into librtlsdr folder, run it from there, and got this 
![rtlsdrscan-screen](https://cloud.githubusercontent.com/assets/9025818/9546631/15a46a0a-4d9d-11e5-89a9-c2ca486f9fd6.png)

**Comment by keerah** [comment]
Repeated with 32bit version. Worked fine! Gonna test it further.
