### ISSUE TITLE
Command Line Interfaces wrong description of parameters for --dwell or function lacking of Sec to ms transformation

### ISSUE THREAD

**Issue by Maureen-Hernandez** [EarToEarOak/RTLSDR-Scanner#16]
The proposed documentation on http://eartoearoak.com/software/rtlsdr-scanner/rtlsdr-manual indicates on examples that

Scan from 430 to 436MHz, with a gain of 8.7dB and a dwell of 16ms, saving to 'test.rfs.: rtlsdr_scan.py -s 430 -e 436 -g 8.7 -d 16 test.rf

and the parameter -d 16 is setting the time in seconds, not ms, that's crashing the libusb library at the libusb_control_transfer.

On the other side there are two -d parametes on the function call (page 21 on the manual)

-d, --delay Delay between sweeps in seconds.

-d, --dwell Dwell time in seconds (optional, default – 131ms).

**Comment by EarToEarOak** [comment]
Thanks.

The dwell range has been limited in 4b45dfa6da7adc791fe622a2a155cee496ba8b70 and the manual updated in ba390ba5d5dc29a79cae42d9fce88145b644cc9e and I eventually remembered to fix the switch documentation in 51ea2b9713884734829675521b89c1f057861706!
