### ISSUE TITLE
Measurement info source

### ISSUE THREAD

**Issue by taismi** [EarToEarOak/RTLSDR-Scanner#18]
Seems that measurements info like Mean and GMean are taken from latest sweep even if average graph is selected. The measurement info should be taken from the graph type that is selected or there should be an option for choosing the latest or the average graph.

**Comment by EarToEarOak** [comment]
I think you're right as it's more intuitive.

At the moment the average is calculated by the plotting routines as these functions vary with the plot type.
I'll look into restructuring the code to base the measurements on this data.
