### ISSUE TITLE
Scan hangs during the ~5% of the scan (Windows)

### ISSUE THREAD

**Issue by Alex131089** [EarToEarOak/RTLSDR-Scanner#20]
Maybe related to #13, but for me the scan hangs a short time after the scan starts in latest versions.
Latest working version is v1.0.21972.32419. I tried to let it run a bit, with the display mode to "Status", but it seems to run forever.

On some of my tries I had a PLL lock error message.

Env : Win8, NooElec Mini 2+

**Comment by EarToEarOak** [comment]
Do you know which version of matplotlib you are using?

**Comment by Alex131089** [comment]
I'm using the standalone version (I should have tell this before), so the one included.

**Comment by EarToEarOak** [comment]
Does the command 'rtl_test' or any other program (such as SDR#) work without problems?

**Comment by Alex131089** [comment]
No big problem with SDR# (sdr_test not tested) and with version 1.0.21972.32419 it's ok

**Comment by leitao** [comment]
I have the very same problem here. After a while, on long frequency scans, the window hangs and I am not able to recover.
