### ISSUE TITLE
Windows 10 Standalone - import error for librtlsdr

### ISSUE THREAD

**Issue by tpainter** [EarToEarOak/RTLSDR-Scanner#22]
The stand alone executable doesn't seem to work on Windows 10 (used v1.0.22298.18049 release download.)

The error that is displayed in the window is:

> Import error: Error loading librtlsdr. Make sure librtlsdr (and all of its dependencies) are in your path
> 
> Error importing libraries
> Press [Return] to exit
> Traceback (most recent call last):
>   File "<string>", line 41, in <module>
> NameError: name 'exit' is not defined
> rtlsdr_scan returned -1

The proper drivers are installed and working, e.g. SDR# works fine.

**Comment by EarToEarOak** [comment]
Try downloading the [RTLSDR driver](http://sdr.osmocom.org/trac/attachment/wiki/rtl-sdr/RelWithDebInfo.zip) and make sure it's in your path.

**Comment by EarToEarOak** [comment]
Another thought: make sure you use the files from the x64 directory for stand alone version.

**Comment by tpainter** [comment]
Seems like the issue was x64 vs x32. It is working now.

**Comment by EarToEarOak** [comment]
Glad to hear its' working.  I'll get round to updating the documentation soon to make it clearer.
