### ISSUE TITLE
Desktop file for Linux

### ISSUE THREAD

**Issue by yarda** [EarToEarOak/RTLSDR-Scanner#25]
I am attaching desktop file for Linux. Currently it suppose that the main executable is located in the /usr/bin. Maybe it could use some variable and substitute the path to be more generic. I am not sure where you want to add it, so I am attaching it and not doing PR, but I could do PR if you prefer it.

[desktop-file.zip](https://github.com/EarToEarOak/RTLSDR-Scanner/files/364053/desktop-file.zip)

**Comment by EarToEarOak** [comment]
Thank you

I'll bear this in mind while considering #24

**Comment by drws** [comment]
@EarToEarOak please also consider this corrected .desktop file, the first one has a few errors in it:

    [Desktop Entry]
    Version=1.0
    Type=Application
    Name=RTLSDR Scanner
    Comment=A cross platform Python frequency scanning GUI for the OsmoSDR rtl-sdr library
    Exec=rtlsdr_scan
    Icon=/opt/rtlsdr-scanner/rtlsdr_scan.ico
    Categories=HamRadio;

**Comment by EarToEarOak** [comment]
Duplicate of #24
