### ISSUE TITLE
It's unclear whether the license of the project is GPLv3 or GPLv3+

### ISSUE THREAD

**Issue by yarda** [EarToEarOak/RTLSDR-Scanner#26]
Hi, in the Manual.pdf there is written:
> Both this document and the RLTSDR Scanner is licensed under the GNU General Public License
> version 3 (http://www.gnu.org/licenses/gpl.html).

but in the readme.md there is:
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation, either version 3 of the License, or
> (at your option) any later version.

So is it released under GPLv3 or GPLv3+? This should be updated in the docs.

**Comment by EarToEarOak** [comment]
It's v3, I've updated the docs in b55e5a47075876962a4d2fc07b541e84f3910cd1.
