### ISSUE TITLE
Measurements During Scans

### ISSUE THREAD

**Issue by funkhoam** [EarToEarOak/RTLSDR-Scanner#30]
I noticed on an older version of the scanner (I believe I downloaded it around Feb-April of 2016) that one of the measurements taken during scans was of dB/sqrt(hz) - how does this measure up to dB/Hz or dBm? Thanks!

**Comment by EarToEarOak** [comment]
My mistake, there shouldn't be a square root in there.
I'll update the code soon.

**Comment by EarToEarOak** [comment]
Updated in 009f67f4fcf4d8d1a3edf7731764701cf0b9575b, the packages will be available shortly.
