### ISSUE TITLE
How to open this GUI interface?

### ISSUE THREAD

**Issue by happybasic** [EarToEarOak/RTLSDR-Scanner#36]
I see the GUI interface form internet, but I can't found.... (I installed RTLSDR Scanner by rtlsdr_scanner-setup-win32.exe) ...  How to open it? Thanks  a lot.

http://www.hellocq.net/forum/attachment/Mon_1401/13_80349_e447b427c1d4ffd.gif?38

**Comment by EarToEarOak** [comment]
You should be able to find it from the Start Menu.  Look for the RTLSDR Scanner folder under 'All Programs'.

**Comment by natiya** [comment]
I also don't know how to open the GUI. My RTLSDR Scanner folder's got lots of python files. Which one should I run? Is that the way to open the GUI?

**Comment by EarToEarOak** [comment]
No response, closing.
