### ISSUE TITLE
Windows Installer 1.3.1 erroneously reports it is not up-to-date

### ISSUE THREAD

**Issue by GeoffMaciolek** [EarToEarOak/RTLSDR-Scanner#40]
The `rtl_scanner-setup-win32.exe` [1.3.1](https://github.com/EarToEarOak/RTLSDR-Scanner/releases/tag/v1.3.1) installer from the [release page](https://github.com/EarToEarOak/RTLSDR-Scanner/releases) incorrectly reports that it is not up to date.  The logic for this check is source for `rtlsdr_scanner.nsi`, currently [lines 336-359](https://github.com/EarToEarOak/RTLSDR-Scanner/blob/b07f7130a58c29f86f5c5ad047946ee61e480d90/nsis/rtlsdr_scanner.nsi#L336-L359). I will attempt a pull request to at least update this request URL, but I haven't yet made sense of the logic that checks for an update, but it appears it references `https://raw.github.com/EarToEarOak/RTLSDR-Scanner/master/nsis/_version` - i.e. [this file](https://github.com/EarToEarOak/RTLSDR-Scanner/blob/master/nsis/_version) in the repository.

(See also #41 - installer launches incorrect update URL)

**Comment by EarToEarOak** [comment]
Re-building the installer seems to have fixed this issue.
