### ISSUE TITLE
Wrong 1.3.1 version reported by the 1.3.2 release

### ISSUE THREAD

**Issue by yarda** [EarToEarOak/RTLSDR-Scanner#46]
Hi,

I downloaded 1.3.2 release from:
https://github.com/EarToEarOak/RTLSDR-Scanner/archive/v1.3.2.tar.gz

but it presents as 1.3.1, because there is:
$ tail -1 rtlsdr_scanner/version.py 
VERSION = [1, 3, 1]

**Comment by EarToEarOak** [comment]
Fixed in 3c032de1aa4783d38a45956b9ce266bf0d01d1af
